language: ruby
rvm:
- 2.2.2
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: NrHifi9RxBF0nk/Z4JLgLNnsN6tEDNTdCyNfNLBXh2BkcSzBKA7NbApwVP0M01knxTRQPAnKTQ6Slewe2AmnbrtpyPx+obmnLxCMGNX+Gcdmt/3eWCntN4EbjnlY9NXyrYdlVVc4lPVe0gTfauN4jpZsVFrSEzJ9WEhu5UGnBIw4JKcqHNFgQR8mp5OhaMNv9cR6Rusl6ZEiV7FqZi1T1wjkx8ZsumvwIjaKJZobqhwquzmSpTwLPjBg/QeeqJ2clNQYPWvlsmifCeyb7dX3BBmkQuLQAIQopOWThqkUTXj2Ts+lKl2h1htRtt0f73CWlb1+7EvD/oZ12zzgrurS2A2rHbOXJOAeHiXqG3YPLASXdCnj69qheyGG9uDuTocKr990sCZvfiVHJF/Sl9TVtYsNy3owdJjKrhOSiGc7cxeOMLIVAalfzp0TETVIOLBEubMDDVQ8ItCMCfy++kJ1RecRLrHEmn5ujDJfE1INNTxYU2RtcedemaWJnupDhLJfl48LWB0pYL/b3QnJ8NAPvbU5+tIlStGzEdQ8M/3XFu/tmif6w1DTh4OcHD6Xi3EuPIY8/gFRGeFkyEsDOQ+NvXd50leM4J/CV0xanb4grzlrc17uFQRoDqDtdhgnbCVxyznqbtCDAnWs4GACeEN0ybS2+nkz+tul65koM01ZTYI=
  app: 'yes'
  on:
    repo: tiy-hou-q3-2015-rails/Musik
  run:
    - "rake db:migrate"
    - "rake cleanup"
